-- album_photo table
SET CURRENT_SCHEMA=RCZ92613;

DROP TABLE ALBUM_PHOTO;
CREATE TABLE ALBUM_PHOTO(
	ALBUM_PHOTO_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	ALBUM_ID BIGINT NOT NULL,
	"URL" VARCHAR(500) NOT NULL,
    DELETE_FLAG INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL, 
    MODIFIED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (ALBUM_PHOTO_ID)
);

