-- album table
SET CURRENT_SCHEMA=RCZ92613;

DROP TABLE ALBUM;
CREATE TABLE ALBUM(
	ALBUM_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	COMMUNITY_ID BIGINT NOT NULL,
	ALBUM_NAME VARCHAR(64) NOT NULL,
    DELETE_FLAG INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL, -- timezoneはapiで設定
    MODIFIED_AT TIMESTAMP NOT NULL, -- timezoneはapiで設定
	PRIMARY KEY (ALBUM_ID)
);