-- event table
SET CURRENT_SCHEMA=RCZ92613;

DROP TABLE EVENT;
CREATE TABLE EVENT(
	EVENT_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	COMMUNITY_ID BIGINT NOT NULL,
	TITLE VARCHAR(32) NOT NULL,
	"START" TIMESTAMP NOT NULL,
	"END" TIMESTAMP NOT NULL,
	LOCATION VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500),
	THUMBNAIL_IMG VARCHAR(500),
    DELETE_FLAG INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL, -- timezoneはapiで設定
    MODIFIED_AT TIMESTAMP NOT NULL, -- timezoneはapiで設定
	PRIMARY KEY (EVENT_ID)
);