-- user_community_relation table
SET CURRENT_SCHEMA=RCZ92613;

-- 更新は行わない
-- TRXのように溜める
-- 論理削除ではなく物理削除
DROP TABLE USER_COMMUNITY_RELATION;
CREATE TABLE USER_COMMUNITY_RELATION(
	COMMUNITY_ID BIGINT NOT NULL,
	"USER_ID" BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL, -- timezoneはapiで設定
	PRIMARY KEY (COMMUNITY_ID,"USER_ID")
);